### ISSUE TITLE
Possible issue with ~ operator in Chrome-web

### ISSUE THREAD

**Issue by hallr-boulder** [marchdev-tk/google_polyline_algorithm#1]
In the decodePolyline method the ~ operator is used. I don't believe that this operator works as expected on Chrome. If you run the example in the library the negative longitudes are incorrect as a result. Things are fine on Android.

Windows 10/64 bit

A possible fix/workaround:

      final coordinateChange =
      //(result & 1) != 0 ? ~(result >> 1) : (result >> 1);
      (result & 1) != 0 ? (~BigInt.from(value)).toInt() : value;

![image](https://user-images.githubusercontent.com/76707233/107580472-d615c100-6bb3-11eb-93b7-b6163e77b24a.png)

**Comment by OlehMarch** [comment]
Thanks for this issue and for the fix as well. It is already present in pub under 3.1.0 version

**Comment by hallr-boulder** [comment]
Thanks for your help!
