### ISSUE TITLE
'List<List<String>>' is not a subtype of type 'List<List<num>>' in type cast

### ISSUE THREAD

**Issue by sumitrvi** [marchdev-tk/google_polyline_algorithm#3]
Error:type 'List<List<String>>' is not a subtype of type 'List<List<num>>' in type cast

When I'm trying to pass a list of coordinates to encode getting the above issue.

Example:List of coordinates
[[26.7784002, 75.8425027], [26.7786778, 75.8425991], [26.7787995, 75.8428689], [26.7787386, 75.8431947], [26.7786963, 75.8435242], [26.7788872, 75.8437456], [26.7790054, 75.843449], [26.77906, 75.8431203], [26.7791082, 75.8428205], [26.7791817, 75.8425138], [26.7790115, 75.8422522], [26.7790001, 75.8419491], [26.7792244, 75.8417791], [26.7794847, 75.8418831], [26.7794877, 75.8421887], [26.7792773, 75.8424163], [26.7790088, 75.8422836], [26.7787782, 75.8421037], [26.7784653, 75.8420592], [26.7781823, 75.8420604], [26.7781429, 75.8423668]]

Some code of snapshot below
List<String> temp=[];
                for (int j = 0; j < getRoutesData!.data![i].routeCoordinates!.length; j++)
                {
                  temp.add([getRoutesData!.data![i].routeCoordinates![j].lat,
                    getRoutesData!.data![i].routeCoordinates![j].lng].toString());
                }
                getRoutesData!.data![i].dataList.add(temp);
                getRoutesData!.data![i].dataString=getRoutesData!.data![i].dataList.join(','+' ');
               getRoutesData!.data![i].encodedString=encodePolyline(getRoutesData!.data![i].dataList as List<List<num>>);

**Comment by OlehMarch** [comment]
@sumitrvi all you need to do is to map all your coords to `num` from `String`
